version: '3.8'

services:
  app:
    build:
      context: .
    container_name: laravel_app
    volumes:
      - .:/var/www
    networks:
      - laravel

  web:
    image: nginx:alpine
    container_name: laravel_web
    ports:
      - 8000:80
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  db:
    image: mysql:5.7
    container_name: laravel_db
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel

volumes:
  dbdata:

networks:
  laravel:
